export const mainConfig = {
  SHIMMER_BAND_WIDTH: 120,
  SKELETON_FACTORY_GAP: 10,
  SKELETON_FACTORY_PADDING: 10,
  SKELETON_FACTORY_DEFAULT_RECT: { width: 200, height: 200 },
  SKELETON_FACTORY_DEFAULT_ROUND_BORDER_RADIUS: 12,
  SKELETON_FACTORY_DEFAULT_CIRCLE_R: 24,
};
